### ISSUE TITLE
Frequent API call freezes the Figma desktop app

### ISSUE THREAD

**Issue by fallingleaflun** [figma/plugin-samples#174]
The following snippet calls `figma.createRectangle()` inside a for-loop. If msg.count is a large number, the Figma desktop app freezes until all the createRectangle calls complete. I'm hoping the Figma desktop app can still handle simple inputs (e.g., moving the canvas) while processing the createRectangle calls. I'm curious if the Figma desktop app can distinguish between calls made by the plugin API and those invoked by user input, and prioritize processing those simple user inputs.
```typescript
figma.ui.onmessage = (msg) => {
  if (msg.type === "create-rectangles") {
    const nodes = [];

    for (let i = 0; i < msg.count; i++) {
      const rect = figma.createRectangle();
      rect.x = i * 150;
      rect.fills = [{ type: "SOLID", color: { r: 1, g: 0.5, b: 0 } }];
      figma.currentPage.appendChild(rect);
      nodes.push(rect);
    }

    figma.currentPage.selection = nodes;
    figma.viewport.scrollAndZoomIntoView(nodes);
  }

  figma.closePlugin();
};
```

**Comment by akbarbmirza** [comment]
I don't believe we currently distinguish between calls made by the plugin API and those invoked by user input - since both run in the main thread.

The right place to report your feedback would be via support@figma.com. It would be extra helpful if you could describe the particular use cases that you think this would be helpful in when you report your feedback.
