### ISSUE TITLE
enable multiple plugins to run simultaneously

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [figma/plugin-samples#24]
Use case

- add a chat like feature
- add a data chart from external source that keeps updating
- enable document changes listener to inform an external entity

**Comment by adispezio** [comment]
This is something the team has considered! For now, plugins can only run one at a time. You can use an external realtime database to keep data in sync for multiple users (such as a chat feature) but will need to open the plugin to fetch updates from the database. Plugins can also remain open and continually poll for changes to data sources. More details on some future proposals here: https://www.figma.com/plugin-docs/whats-supported/

As for document listeners, there are Webhooks available for some actions that might be helpful: https://www.figma.com/developers/api#webhooks_v2

**Comment by slt-uxd** [comment]
In terms of use cases, this would open up an entire new class of Figma plugins, that behave more like toolbars, rather than modal dialogs. Maybe Figma can allow up to 5 plugins to run simulatneously. This would allow the user to have 4 plugin toolbars (left, top, right, bottom), and 1 modal plugin running at any given time. 

Or @adispezio do you think it would be too much running at once for Figma to handle?

**Comment by AlexisG0** [comment]
Hi, sorry to dig up this topic but maybe this will help others in the future.
A plugin is now available and allows to navigate between different plugins ;) 

https://www.figma.com/community/plugin/1200708084659766553/
