### ISSUE TITLE
Example of how to use multiple .html files

### ISSUE THREAD

**Issue by stichiboi** [figma/plugin-samples#28]
Hello!
I've recently started developing a plugin for Figma. 
I have a user interface that should:

1. Ask the user for a login token
2. Then load the main UI

At the moment I have my two html files: ui.html and main.html.
From the ui.html, I have the classic:
`window.location.href = 'html/main.html'`
rigged to a button.

If I test it in the browser, it all works fine, the page changes normally.
But when I run it in Figma:
`Uncaught DOMException: Failed to set the 'href' property on 'Location': 'html/main.html' is not a valid URL.
    at HTMLButtonElement.document.getElementById.onclick (<anonymous>:1080:30)`

This is my webpack config file. I've taken most of it from the webpack sample, and tried to modify it a bit, but I'm no expert, so this might be the issue. I'm just dazzled that if I debug in Chrome, everything works fine.

```
const HtmlWebpackInlineSourcePlugin = require('html-webpack-inline-source-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const path = require('path')
const webpack = require('webpack')

module.exports =
    //Client Config
    (env, argv) => ({
        mode: argv.mode === 'production' ? 'production' : 'development',

        // This is necessary because Figma 'eval' works differently than normal eval
        devtool: argv.mode === 'production' ? false : 'inline-source-map',

        entry: {
            ui: './src/ts/ui.ts', // The entry point for your UI code
            code: './src/ts/code.ts', // The entry point for your plugin code
        },

        module: {
            rules: [
                // Converts TypeScript code to JavaScript
                {test: /\.tsx?$/, use: 'ts-loader', exclude: /node_modules/},

                // Enables including CSS by doing "import './file.css'" in your TypeScript code
                {
                    test: /\.css$/,
                    use: [
                        'style-loader',
                        'css-loader'
                    ]
                },

                {
                    test: /\.html$/,
                    use: [{
                        loader: "file-loader",
                        options: {
                            name: '[name].[ext]',
                            outputPath: 'html/',
                            publicPath: 'html/'
                        }
                    }],
                    exclude: path.resolve(__dirname, 'src/html/ui.html') // Exclude ui.html since it gets loaded from the plugin
                },

                // Allows you to use "<%= require('./file.svg') %>" in your HTML code to get a data URI
                {test: /\.(png|jpg|gif|webp|svg|zip)$/, loader: [{loader: 'url-loader'}]},
            ],
        },

        // Webpack tries these extensions for you if you omit the extension like "import './file'"
        resolve: {extensions: ['.tsx', '.ts', '.jsx', '.js']},

        output: {
            filename: '[name].js',
            path: path.resolve(__dirname, 'dist'), // Compile into a folder called "dist"
        },

        // Tells Webpack to generate "ui.html" and to inline "ui.ts" into it
        plugins: [
            new webpack.DefinePlugin({
                'global': {} // Fix missing symbol error when running in developer VM
            }),
            new HtmlWebpackPlugin({
                template: './src/html/ui.html',
                filename: 'ui.html',
                inlineSource: '.(js)$',
                chunks: ['ui'],
            }),
            new HtmlWebpackInlineSourcePlugin(),
        ],
    })

```

**Comment by adispezio** [comment]
While it does seem like that should work, there's some complexity to the plugin architecture that won't allow you to use traditional href links to navigate to a new page. [This page in the Plugin Docs explains](https://www.figma.com/plugin-docs/how-plugins-run/) in a bit more detail. Basically, you can think of the UI as a single-page app. All the code needed to run the UI should be injected when the UI loads. This kind of architecture uses clever approaches to hiding/showing parts of the DOM to create the effect of multiple pages. This could be as simple as a javascript variable that stores the current 'page' and then uses other code to decide what is being shown at that time. A view library like React can also help in this scenario as it can manage what is currently being show to the user in a "side-effect-free" way. Quick note on approaches like React is that you won't need true 'routing' so you can keep it simpler than that :). [Here's a more recent example using React Hooks](https://github.com/adispezio/figma-plugin-example-prototype-write) to track the 'state' of the plugin UI - this is more advanced than you need but might help to break it down conceptually.

For now I'm going to close this due to inactivity but will consider adding a multi-page example!

**Comment by gauravmandal1** [comment]
Hey can you please add a multi-page example because i am struggling to do so

**Comment by ashu5398** [comment]
I am also facing this issue, It will be very nice if you can add an example for this problem that will be helpful for everyone.
