### ISSUE TITLE
React Code.ts debug

### ISSUE THREAD

**Issue by ellunium** [figma/plugin-samples#7]
Hi, 

How can I debug the code.ts file using the [react sample](https://github.com/figma/plugin-samples/tree/master/react)?
I see all other files available in the source panel webpack://./src, but not the code.ts, so there's no way I can set breakpoints there.

Help please :D 

Thanks!

**Comment by ellunium** [comment]
Bump :)

**Comment by evanw** [comment]
Sorry, just came across this issue now (we use [a Slack group](https://figmaplugins.slack.com/) for these types of discussions). Doing this is difficult because of the sandbox, but can be done:

1. First, enable the developer VM. Right click on the canvas and choose `Plugins > Development > Use Developer VM` to make sure it's checked. This runs your code in a browser-based sandbox instead of the secure sandbox that will be used when you release your plugin, which lets you add breakpoints.

2. Add a `debugger;` statement to the top of your `code.ts` file. This is necessary because the `code.ts` source won't be visible in the source panel since it's an anonymous source due to the sandbox.

3. Open the developer console with `Plugins > Development > Open Console`.

4. Run your plugin.

5. The debugger should break at your debugger statement. From there you can add breakpoints and click the play button to resume editing.
